; PlatformIO Project Configuration File

[platformio]
default_envs = bridge

[env:matter_smoke]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
board_build.partitions = partitions.csv
build_type = release
build_src_filter =
	-<*>
	+<matter_smoke.cpp>

build_flags =
	-D CONFIG_ESP_MATTER_ENABLE_DATA_MODEL=1
	-D CONFIG_ENABLE_CHIPOBLE=1
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Matter/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32/include/esp_matter
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
	-std=gnu++17

lib_deps =

lib_ldf_mode = chain+
lib_compat_mode = strict

[env:bridge]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_type = release
build_src_filter =
	+<*>
	-<matter_smoke.cpp>

build_flags =
	-D USE_MQTT_BROKER=0
	-D USE_MQTT_CLIENT=1
	-D DIAG_LOG_ENABLED=1
	-D LOGGING=0
	-D BROKER_DEBUG_LEVEL=DEBUG_NONE
	-D CORE_DEBUG_LEVEL=0
	-D CONFIG_ESP_MATTER_ENABLE_DATA_MODEL=1
	-D CONFIG_ENABLE_CHIPOBLE=1
	-D BRIDGE_MATTER_ENABLED=1
	-D BUILD_TRIGGER=\"${PIOENV}\"
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Matter/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32/include/esp_matter
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src
	-std=gnu++17
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DNDEBUG
	-Wall
	-Wextra
	-Wno-missing-field-initializers
	-Wno-deprecated-declarations
	-Wno-format

lib_deps = 
	bblanchon/ArduinoJson@^7.4.0
	https://github.com/ESP32Async/ESPAsyncWebServer.git
	marvinroger/AsyncMqttClient
	https://github.com/ESP32Async/AsyncTCP.git
	ayushsharma82/ElegantOTA@^3.1.7

lib_ldf_mode = chain+
lib_compat_mode = strict
lib_ignore = AsyncTCP_RP2040W
extra_scripts =
	pre:update_version_in_code.py
	post:update_backup_projekt_and_firmware.py

[env:bridge_noble]
extends = env:bridge
build_flags =
	${env:bridge.build_flags}
	-UCONFIG_ENABLE_CHIPOBLE
	-D CONFIG_ENABLE_CHIPOBLE=0

