; PlatformIO Project Configuration File

[platformio]
default_envs = bridge

[env:bridge]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_type = release

build_flags =
<<<<<<< HEAD
=======
	-D USE_TEDEE=0
	-D USE_NUKI=0
	-D USE_DHT=0
	-D USE_TELEGRAM=0
	-D USE_TELEGRAM_CMD=0
	-D USE_DOWNLOAD_UPLOAD=0
>>>>>>> 937c36a21b29111ed2f16fbabeffa236a6d16872
	-D USE_MQTT_BROKER=1
	-D USE_MQTT_CLIENT=1
	-D DIAG_LOG_ENABLED=1
	-D LOGGING=1
	-D BROKER_DEBUG_LEVEL=DEBUG_NONE
	-D BUILD_TRIGGER=\"${PIOENV}\"
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER
	-std=gnu++17
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DNDEBUG
	-Wall
	-Wextra
	-Wno-missing-field-initializers
	-Wno-deprecated-declarations
	-Wno-format

lib_deps = 
	https://github.com/ESP32Async/ESPAsyncWebServer.git
	marvinroger/AsyncMqttClient
	https://github.com/ESP32Async/AsyncTCP.git
	ayushsharma82/ElegantOTA@^3.1.7

lib_ldf_mode = deep+
lib_compat_mode = strict
lib_ignore = AsyncTCP_RP2040W
extra_scripts =
	pre:update_version_in_code.py
	post:update_backup_projekt_and_firmware.py
